apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-suspicious-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      suspicious: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
