apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sallowedrepos
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedRepos
      validation:
        openAPIV3Schema:
          properties:
            repos:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedrepos

        violation[{"msg": msg}] {
          input.review.object.spec.containers[_].image
          not input.review.object.spec.containers[_].image in {repo | repo := input.parameters.repos[_]}
          msg := sprintf("The image '%v' is not allowed. Allowed repos are: %v", [input.review.object.spec.containers[_].image, input.parameters.repos])
        }
